language: node_js
node_js:
    - "0.12"
branches:
  except:
      - /^v[0-9]/
before_install:
    - sudo apt-get update -y -qq
    - sudo apt-get install -y librsvg2-bin graphviz plotutils
    - npm install -g npm
before_script:
    - npm install -g grunt-cli
